- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
    use: "systemd"

- name: Configure Core Params
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    reload: true
  loop:
  - name: net.ipv4.tcp_slow_start_after_idle
    value: "0"
  - name: net.ipv4.tcp_mtu_probing
    value: "0"
  - name: net.ipv4.tcp_notsent_lowat
    value: "65536"
  - name: net.ipv4.ip_local_port_range
    value: "1024 65535"
  - name: net.ipv4.tcp_tw_reuse
    value: "1"
  - name: net.core.somaxconn
    value: "81960"

- name: Install Packages
  ansible.builtin.apt: 
    name: "{{ lb_packages }}"
    state: latest
    update_cache: true

- name: Configure nginx for proxy to apps
  ansible.builtin.template:
    src: "templates/lb.conf.j2"
    dest: "/etc/nginx/conf.d/lb.conf"
    owner: www-data
    group: www-data
  notify: nginx reload

- name: Remove default config
  ansible.builtin.file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  notify: nginx reload

- name: Copy nginx.conf
  ansible.builtin.copy:
    src: "files/nginx.conf"
    dest: "/etc/nginx/nginx.conf"
    owner: root
    group: root
    mode: "0644"
  notify: nginx reload

- name: Install aws cli (for keepalived)
  ansible.builtin.pip:
    name: awscli

- name: Create dir for aws config
  ansible.builtin.file:
    path: "/root/.aws"
    state: directory

- name: Copy aws cli config
  ansible.builtin.copy:
    dest: "/root/.aws/config"
    content: |
      [default]
      output = json
      region = US
      endpoint_url = https://api.cloud.croc.ru:443

- name: Copy aws cli credentials
  ansible.builtin.copy:
    src: "files/aws_credentials.conf"
    dest: "/root/.aws/credentials"    

- name: Configure Keepalived
  ansible.builtin.template:
    src: "templates/keepalived.conf.j2"
    dest: "/etc/keepalived/keepalived.conf"
    owner: root
    group: root
    mode: "0644"
  notify: restart keepalived

- name: Configure master script
  ansible.builtin.template:
    src: "templates/master.sh.j2"
    dest: "/etc/keepalived/master.sh"
    owner: root
    group: root
    mode: "0755"
  notify: restart keepalived

